require("pack.lsp-config")
require("pack.telescope")
require("pack.no-neck-pain")
require("pack.outline")
require("pack.gitsigns")
require("pack.everforest")
require("pack.oil")
require("pack.mini-files")
require("pack.ts-comments")
require("pack.conform")
require("pack.dropbar")

vim.cmd.packadd('nvim.undotree')
